import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Github, Linkedin, Instagram, Facebook } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
// import HoverSoundElement from "@/components/hover";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-stone-100`}
      >
          <header className="p-16">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex mb-6 md:mb-0 gap-4">
              <h1 className="text-4xl font-bold mb-2">Spy</h1>
              <h1 className="text-4xl font-bold mb-2">スパイ</h1>
              <h1 className="text-4xl font-bold mb-2">สปาย</h1>
            </div>
            
            <div className="flex space-x-4">
              <Link href="https://github.com/phattradaa" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="icon">
                  <Github className="h-6 w-6" />
                </Button>
              </Link>
              <Link href="https://www.linkedin.com/in/phattrada-mikota-549a5123b/" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="icon">
                  <Linkedin className="h-6 w-6" />
                </Button>
              </Link>
              <Link href="https://github.com/phattradaa" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="icon">
                  <Instagram className="h-6 w-6" />
                </Button>
              </Link>
              <Link href="https://www.facebook.com/share/1AMgZFmRdi/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="icon">
                  <Facebook className="h-6 w-6" />
                </Button>
              </Link>
            </div>
          </div>
        </header>
        <div className="px-16 py-5">
          {children}
        </div>
      </body>
    </html>
  );
}